#############################################################################
# Makefile for building: mythteatime
# Generated by qmake (2.01a) (Qt 4.8.4) on: Mon Mar 11 12:40:59 2013
# Project:  mythteatime.pro
# Template: subdirs
# Command: /usr/bin/qmake QMAKE=/usr/bin/qmake -o Makefile mythteatime.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-mythteatime

mythteatime/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) mythteatime/ || $(MKDIR) mythteatime/ 
	cd mythteatime/ && $(QMAKE) /storage/home/tob/github/mythteatime/mythteatime/mythteatime.pro QMAKE=/usr/bin/qmake -o $(MAKEFILE)
sub-mythteatime-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) mythteatime/ || $(MKDIR) mythteatime/ 
	cd mythteatime/ && $(QMAKE) /storage/home/tob/github/mythteatime/mythteatime/mythteatime.pro QMAKE=/usr/bin/qmake -o $(MAKEFILE)
sub-mythteatime: mythteatime/$(MAKEFILE) FORCE
	cd mythteatime/ && $(MAKE) -f $(MAKEFILE)
sub-mythteatime-make_default: mythteatime/$(MAKEFILE) FORCE
	cd mythteatime/ && $(MAKE) -f $(MAKEFILE) 
sub-mythteatime-make_first: mythteatime/$(MAKEFILE) FORCE
	cd mythteatime/ && $(MAKE) -f $(MAKEFILE) first
sub-mythteatime-all: mythteatime/$(MAKEFILE) FORCE
	cd mythteatime/ && $(MAKE) -f $(MAKEFILE) all
sub-mythteatime-clean: mythteatime/$(MAKEFILE) FORCE
	cd mythteatime/ && $(MAKE) -f $(MAKEFILE) clean
sub-mythteatime-distclean: mythteatime/$(MAKEFILE) FORCE
	cd mythteatime/ && $(MAKE) -f $(MAKEFILE) distclean
sub-mythteatime-install_subtargets: mythteatime/$(MAKEFILE) FORCE
	cd mythteatime/ && $(MAKE) -f $(MAKEFILE) install
sub-mythteatime-uninstall_subtargets: mythteatime/$(MAKEFILE) FORCE
	cd mythteatime/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: mythteatime.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		libs.pro \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) QMAKE=/usr/bin/qmake -o Makefile mythteatime.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
libs.pro:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) QMAKE=/usr/bin/qmake -o Makefile mythteatime.pro

qmake_all: sub-mythteatime-qmake_all FORCE

make_default: sub-mythteatime-make_default FORCE
make_first: sub-mythteatime-make_first FORCE
all: sub-mythteatime-all FORCE
clean: sub-mythteatime-clean FORCE
distclean: sub-mythteatime-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-mythteatime-install_subtargets FORCE
uninstall_subtargets: sub-mythteatime-uninstall_subtargets FORCE

sub-mythteatime-check: mythteatime/$(MAKEFILE)
	cd mythteatime/ && $(MAKE) -f $(MAKEFILE) check
check: sub-mythteatime-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

